version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
      ruby: 2.7
    commands:
      - echo "install phase..."
      - apt-get update
      - apt-get install -y jq
  build:
    commands:
      - echo "build phase..."
      - sh release.sh
